version: '3.1'

services:
  web:
    build:
      context: .
    ports:
      - "3333:3333"
    environment:
      - GDEMO_DB_PATH=root:password@tcp(db:3306)/demogowsdb?charset=utf8mb4&parseTime=True
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demogowsdb
    volumes:
      - ./dockersql:/docker-entrypoint-initdb.d

